/**
 * Restate the design system's custom properties for the type checker (`UI-1c`).
 *
 * The seven files in `design-system/tokens/` stay the source of truth -- they are what the
 * browser reads, what the seventeen specimen cards `<link>`, and what a designer edits. This
 * script reads them and writes `design-system/tokens.ts`, so the same names exist as a union
 * that `tsc` can check a typo against.
 *
 * It is committed output rather than a build step, for the reason `UI-3a` commits an
 * `openapi.json` snapshot: a generated file that is in the repository is one a reviewer can see
 * change, and the check that it is current is a test rather than a stage everybody has to
 * remember to run. `npm run tokens` rewrites it; `design-system-tokens.node.test.ts` fails if it
 * is stale.
 *
 *     npm run tokens
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TOKENS_DIR = join(ROOT, 'design-system', 'tokens');
const OUTPUT = join(ROOT, 'design-system', 'tokens.ts');

/**
 * The custom properties one stylesheet declares, in the order it declares them.
 *
 * Declarations only -- the left-hand side of `--name:`. A `var(--name)` on the right is a use,
 * and `--bg: var(--ink-900)` is one of each on one line, so telling them apart is the whole job
 * here. Comments come out first: this file's own prose names tokens it is not declaring.
 *
 * @param {string} css
 * @returns {string[]}
 */
export function tokensIn(css) {
  const names = [];
  const rules = css.replace(/\/\*[\s\S]*?\*\//g, '');
  for (const match of rules.matchAll(/(?:^|[;{])\s*(--[a-z0-9-]+)\s*:/gi)) {
    const name = match[1];
    if (name !== undefined && !names.includes(name)) names.push(name);
  }
  return names;
}

/**
 * Every custom property the system declares, across all seven files, in file order.
 *
 * @returns {string[]}
 */
export function declaredTokens() {
  const names = [];
  const files = readdirSync(TOKENS_DIR)
    .filter((f) => f.endsWith('.css'))
    .sort();
  for (const file of files) {
    for (const name of tokensIn(readFileSync(join(TOKENS_DIR, file), 'utf8'))) {
      if (!names.includes(name)) names.push(name);
    }
  }
  return names;
}

/**
 * @param {string[]} names
 * @returns {string}
 */
export function render(names) {
  return `/**
 * The design system's tokens, as a type (\`UI-1c\`).
 *
 * **Generated by \`npm run tokens\` from \`design-system/tokens/*.css\`. Do not edit.** The CSS is
 * the source of truth: it is what the browser reads and what the specimen cards link. This file
 * exists so that \`token('--surfce')\` is a compile error rather than a rule the browser silently
 * drops, and it is checked against the CSS by a test so the two cannot drift.
 *
 * Names only. The values are the CSS's business and they change with the theme, which is the
 * whole point of a token -- \`--bg\` is one name and two colours.
 */

export const TOKENS = [
${names.map((n) => `  '${n}',`).join('\n')}
] as const;

/** Any custom property the design system declares. */
export type Token = (typeof TOKENS)[number];

/**
 * A token as a CSS value.
 *
 * \`\`\`ts
 * <div style={{ background: token('--surface') }} />
 * \`\`\`
 *
 * The indirection is small and it is the only thing standing between a component and a literal
 * colour, which is the one rule this system does not bend (\`UI-1i\`).
 */
export function token(name: Token): string {
  return \`var(\${name})\`;
}
`;
}

/* Only when run, never when imported. The test that keeps `tokens.ts` honest imports the two
   functions above and compares their output to the committed file -- and a generator that wrote
   as a side effect of being read would make that test pass by rewriting the thing it is
   checking. */
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const names = declaredTokens();
  writeFileSync(OUTPUT, render(names), 'utf8');
  console.warn(`tokens.ts: ${String(names.length)} tokens from ${TOKENS_DIR}`);
}
